version: '3'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5532:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: foodgo
  test-db:
    image: postgres:13
    ports:
      - 5534:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: foodgo
